"""
updater_app.py — SHA Signal Analysis updater service.

Usage:  python updater_app.py [demo|live]

Architecture
────────────
Forever Loop (runs 24×7):
  Step 1 — Load Fyers token from C:/Ballom_FYR/fyers_token.json
           (written by dev_scanner — NO re-auth here)
  Step 2 — Day-change detection → reload token + holidays
  Step 3 — Read CE/PE pairs from option_pairs.json / commodity_pairs.json
           (generated by dev_scanner)
  Step 4 — For each symbol pair, compute:
             • Signal SHA (length=3) for CE, PE, IDX
             • Trend SHA  (length=6) for CE, PE, IDX
             • Power, List, Crossover for both
             • GAP%  between Signal SHA and Trend SHA
             • SHA Relationship (DIVERGING / CONVERGING / PARALLEL / CLOSE)
  Step 5 — Dump all signal data to JSON state files so the dev branch
           dashboard can display SHA Signal Analysis in real-time

Output:
  C:/Ballom_FYR/state/<mode>/signal_state.json   — per-symbol SHA analysis
  C:/Ballom_FYR/state/<mode>/app_status.json      — updater lifecycle
  C:/Ballom_FYR/state/<mode>/strategy_log/         — scan/update events

Token sharing:  reads token from C:/Ballom_FYR/fyers_token.json
                (written by dev_scanner, refreshed daily at midnight)
"""

import sys
import json
import math
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import date, datetime, time as dt_time
from pathlib import Path
from time import sleep

from fyers import Fyers
from demo_fyers import DemoFyers
from indicator import SmoothedHeikenAshi
from constants import (
    SYMBOLS_JSON,
    OPTION_PAIRS_JSON,
    COMMODITY_PAIRS_JSON,
    INDICES_START,
    INDICES_END,
    COMMODITY_START,
    COMMODITY_END,
    SHA_LENGTH,
    SHA_MA_TYPE,
    SHA_TREND_LENGTH,
    SHA_TREND_MA_TYPE,
    DEFAULT_TIMEFRAME,
    DEFAULT_CANDLES,
)
from state_writer import (
    configure as configure_state_writer,
    write_app_status,
    write_signal_state,
    log_strategy_event,
)

# ── Updater config ─────────────────────────────────────────────────────────────
UPDATE_INTERVAL = 3   # seconds between each full cycle (near real-time)


# ═══════════════════════════════════════════════════════════════════════════════
#  HELPERS
# ═══════════════════════════════════════════════════════════════════════════════

def load_symbols_config() -> dict:
    """Load symbols.json (indices + commodities config)."""
    with open(SYMBOLS_JSON, "r") as f:
        return json.load(f)


def _load_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        with open(path, "r") as f:
            return json.load(f)
    except Exception:
        return {}


# ═══════════════════════════════════════════════════════════════════════════════
#  TOKEN LOADING  (read-only — no re-auth)
# ═══════════════════════════════════════════════════════════════════════════════

def load_fyers_session(fyers: Fyers, force: bool = False) -> bool:
    """
    Load the Fyers token from C:/Ballom_FYR/fyers_token.json.

    This token is written by the dev_scanner branch.  We only READ it
    here — no TOTP login is performed.  If the token is missing or
    expired, we wait for dev_scanner to refresh it.

    Returns True if session is ready, False otherwise.
    """
    try:
        fyers.ensure_session(force=force)
        return True
    except Exception as e:
        log_strategy_event(
            "SYSTEM", "UPDATER", "TOKEN_FAIL",
            details=f"Could not load token: {str(e)[:100]}",
        )
        return False


# ═══════════════════════════════════════════════════════════════════════════════
#  HOLIDAY AWARENESS
# ═══════════════════════════════════════════════════════════════════════════════

def is_trading_day(
    today: date,
    holidays: set[str],
    special_sessions: list[dict],
) -> bool:
    """True if *today* is a valid trading day (holiday/weekend check)."""
    today_str = today.isoformat()
    if any(ss.get("date") == today_str for ss in special_sessions):
        return True
    if today.weekday() >= 5:
        return False
    if today_str in holidays:
        return False
    return True


# ═══════════════════════════════════════════════════════════════════════════════
#  SHA SIGNAL COMPUTATION  (ported from app.py inner_loop Steps B–B4)
# ═══════════════════════════════════════════════════════════════════════════════

def get_symbol_details(
    raw_df,
    sha_length: int = SHA_LENGTH,
    sha_type: str = SHA_MA_TYPE,
):
    """
    Compute Smoothed Heiken-Ashi on *raw_df* (OHLCV) and derive:
        lt_symbol_power  — count of bullish candles in last 7
        lt_symbol_list   — [1|0, ...] most-recent-first
        crossover        — price vs SHA position [-3..-1, 1..3]
        sha_debug        — last 7 SHA OHLC dicts (most-recent-first)

    Returns (lt_symbol_power, lt_symbol_list, crossover, sha_debug).
    """
    lt_sha = SmoothedHeikenAshi.calculate(
        df=raw_df,
        smooth_length=sha_length,
        smooth_ma_type=sha_type,
        after_smooth_length=sha_length,
        after_smooth_ma_type=sha_type,
    )

    threshold = 0
    lt_symbol_power = 0
    lt_symbol_list = []
    crossover = []
    sha_debug = []

    for i in range(-1, -8, -1):
        sha_o = lt_sha["Open"].iloc[i]
        sha_h = lt_sha["High"].iloc[i]
        sha_l = lt_sha["Low"].iloc[i]
        sha_c = lt_sha["Close"].iloc[i]

        # Guard against NaN SHA values (insufficient candles)
        if math.isnan(sha_o) or math.isnan(sha_h) or math.isnan(sha_l) or math.isnan(sha_c):
            lt_symbol_list.append(0)
            crossover.append(-2)
            sha_debug.append({
                "ts": str(raw_df["Timestamp"].iloc[i]) if "Timestamp" in raw_df.columns else "",
                "O": 0, "H": 0, "L": 0, "C": 0, "dir": "NaN",
            })
            continue

        ha_range = abs(sha_h - sha_l)
        if ha_range == 0:
            ha_range = 1e-9

        lt_diff = (sha_c - sha_o) / ha_range

        lt_sha_diff = 1 if lt_diff >= threshold else 0
        lt_symbol_list.append(lt_sha_diff)
        lt_symbol_power += lt_sha_diff

        ct_p_high = raw_df["High"].iloc[i]
        ct_p_low = raw_df["Low"].iloc[i]

        if lt_sha_diff == 1:
            if ct_p_low >= sha_h:
                crossover.append(3)
            elif ct_p_high <= sha_l:
                crossover.append(1)
            else:
                crossover.append(2)
        else:
            if ct_p_high <= sha_l:
                crossover.append(-3)
            elif ct_p_low >= sha_h:
                crossover.append(-1)
            else:
                crossover.append(-2)

        # Diagnostic: SHA OHLC + timestamp for dashboard
        ts = str(raw_df["Timestamp"].iloc[i]) if "Timestamp" in raw_df.columns else ""
        sha_debug.append({
            "ts": ts,
            "O": round(float(sha_o), 2),
            "H": round(float(sha_h), 2),
            "L": round(float(sha_l), 2),
            "C": round(float(sha_c), 2),
            "dir": "BULL" if lt_sha_diff == 1 else "BEAR",
        })

    return lt_symbol_power, lt_symbol_list, crossover, sha_debug


def get_trend_details(
    raw_df,
    sha_length: int = SHA_TREND_LENGTH,
    sha_type: str = SHA_TREND_MA_TYPE,
):
    """
    Compute Trend SHA (longer-period) — same logic as get_symbol_details
    but with longer SHA length for trend identification.
    """
    return get_symbol_details(raw_df, sha_length=sha_length, sha_type=sha_type)


def compute_sha_gap(signal_sha_debug: list, trend_sha_debug: list) -> dict:
    """
    Compute GAP% between Signal SHA and Trend SHA using means.

    GAP% = ((mean_signal_mid - mean_trend_mid) / mean_trend_mid) × 100

    Uses the mean midpoint of each SHA across all candles, with Trend SHA
    (second SHA) as the base. This gives a stable percentage that doesn't
    fluctuate with individual candle ranges.

    Returns dict:
        gap_pct      — the mean-based gap percentage
        signal_mean  — mean midpoint of Signal SHA candles
        trend_mean   — mean midpoint of Trend SHA candles
        per_candle   — per-candle gap data for relationship detection
    """
    n = min(len(signal_sha_debug), len(trend_sha_debug))
    if n == 0:
        return {"gap_pct": 0.0, "signal_mean": 0.0, "trend_mean": 0.0, "per_candle": []}

    sig_mids = []
    trd_mids = []
    per_candle = []

    for i in range(n):
        sig = signal_sha_debug[i]
        trd = trend_sha_debug[i]

        sig_mid = (sig.get("H", 0) + sig.get("L", 0)) / 2
        trd_mid = (trd.get("H", 0) + trd.get("L", 0)) / 2

        sig_mids.append(sig_mid)
        trd_mids.append(trd_mid)

        # Per-candle gap using trend mid as base
        if abs(trd_mid) > 1e-9:
            candle_gap = ((sig_mid - trd_mid) / abs(trd_mid)) * 100
        else:
            candle_gap = 0.0

        per_candle.append({
            "gap_pct": round(candle_gap, 2),
            "signal_mid": round(sig_mid, 2),
            "trend_mid": round(trd_mid, 2),
        })

    signal_mean = sum(sig_mids) / len(sig_mids)
    trend_mean = sum(trd_mids) / len(trd_mids)

    # Gap% using trend mean as base
    if abs(trend_mean) > 1e-9:
        gap_pct = ((signal_mean - trend_mean) / abs(trend_mean)) * 100
    else:
        gap_pct = 0.0

    return {
        "gap_pct": round(gap_pct, 2),
        "signal_mean": round(signal_mean, 2),
        "trend_mean": round(trend_mean, 2),
        "per_candle": per_candle,
    }


def compute_sha_relationship(gap_data: dict) -> dict:
    """
    Analyze the relationship between Signal SHA and Trend SHA based on
    the mean-based GAP% and per-candle gap trend.

    Returns dict with:
        status   : "DIVERGING" | "CONVERGING" | "PARALLEL" | "CLOSE"
        strength : 0.0 – 1.0
        avg_gap  : absolute mean-based GAP%
        delta    : change rate between recent and older halves
    """
    per_candle = gap_data.get("per_candle", [])
    gap_pct = gap_data.get("gap_pct", 0.0)

    if not per_candle or len(per_candle) < 2:
        return {"status": "UNKNOWN", "strength": 0.0, "avg_gap": 0.0, "delta": 0.0}

    avg_gap = abs(gap_pct)

    # CLOSE: SHAs nearly overlapping (mean gap < 1% of trend price)
    CLOSE_THRESHOLD = 1.0
    if avg_gap < CLOSE_THRESHOLD:
        strength = round(1.0 - avg_gap / CLOSE_THRESHOLD, 4)
        return {"status": "CLOSE", "strength": strength,
                "avg_gap": round(avg_gap, 2), "delta": 0.0}

    # Trend analysis: compare recent half vs older half of per-candle gaps
    abs_gaps = [abs(g["gap_pct"]) for g in per_candle]
    mid = len(abs_gaps) // 2
    recent = abs_gaps[:max(mid, 1)]
    older  = abs_gaps[max(mid, 1):]

    avg_recent = sum(recent) / len(recent)
    avg_older  = sum(older) / len(older) if older else avg_recent

    delta = avg_recent - avg_older

    PARALLEL_THRESHOLD = 0.5
    if abs(delta) < PARALLEL_THRESHOLD:
        strength = round(1.0 - abs(delta) / PARALLEL_THRESHOLD, 4)
        return {"status": "PARALLEL", "strength": strength,
                "avg_gap": round(avg_gap, 2), "delta": round(delta, 2)}
    elif delta > 0:
        strength = round(min(1.0, delta / 5.0), 4)
        return {"status": "DIVERGING", "strength": strength,
                "avg_gap": round(avg_gap, 2), "delta": round(delta, 2)}
    else:
        strength = round(min(1.0, abs(delta) / 5.0), 4)
        return {"status": "CONVERGING", "strength": strength,
                "avg_gap": round(avg_gap, 2), "delta": round(delta, 2)}


# ═══════════════════════════════════════════════════════════════════════════════
#  PROCESS ONE SYMBOL PAIR  (fetch history → SHA → dump to JSON)
# ═══════════════════════════════════════════════════════════════════════════════

def process_symbol(
    fyers: Fyers,
    symbol_key: str,
    ce_symbol: str,
    pe_symbol: str,
    underlying: str,
    market_type: str,
    holidays: set[str],
    special_sessions: list[dict],
    timeframe: str = DEFAULT_TIMEFRAME,
    candles: int = DEFAULT_CANDLES,
) -> bool:
    """
    Fetch historical data for CE, PE, IDX and compute full SHA pipeline.
    Writes signal_state.json for this symbol.

    Returns True on success, False on error.
    """
    try:
        # ── Fetch historical OHLCV (CE, PE, IDX in parallel) ──────────
        def _fetch(sym):
            return fyers.fetch_historical_data(
                sym, timeframe, candles,
                market_type=market_type,
                holidays=holidays,
                special_sessions=special_sessions,
            )

        with ThreadPoolExecutor(max_workers=3) as pool:
            fut_ce = pool.submit(_fetch, ce_symbol)
            fut_pe = pool.submit(_fetch, pe_symbol)
            fut_idx = pool.submit(_fetch, underlying)
            ce_df = fut_ce.result()
            pe_df = fut_pe.result()
            idx_df = fut_idx.result()

        # ── Signal SHA (length=3) ─────────────────────────────────────
        ce_power, ce_list, ce_cross, ce_sha_dbg = get_symbol_details(ce_df)
        pe_power, pe_list, pe_cross, pe_sha_dbg = get_symbol_details(pe_df)
        idx_power, idx_list, idx_cross, idx_sha_dbg = get_symbol_details(idx_df)

        # ── Trend SHA (length=6) ──────────────────────────────────────
        ce_t_power, ce_t_list, ce_t_cross, ce_t_sha_dbg = get_trend_details(ce_df)
        pe_t_power, pe_t_list, pe_t_cross, pe_t_sha_dbg = get_trend_details(pe_df)
        idx_t_power, idx_t_list, idx_t_cross, idx_t_sha_dbg = get_trend_details(idx_df)

        # ── GAP% between Signal SHA and Trend SHA ─────────────────────
        ce_gap = compute_sha_gap(ce_sha_dbg, ce_t_sha_dbg)
        pe_gap = compute_sha_gap(pe_sha_dbg, pe_t_sha_dbg)
        idx_gap = compute_sha_gap(idx_sha_dbg, idx_t_sha_dbg)

        # ── SHA Relationship ──────────────────────────────────────────
        ce_rel = compute_sha_relationship(ce_gap)
        pe_rel = compute_sha_relationship(pe_gap)
        idx_rel = compute_sha_relationship(idx_gap)

        # ── Dump to signal_state.json (dashboard-compatible) ──────────
        write_signal_state(
            symbol_key=symbol_key,
            ce_symbol=ce_symbol,
            pe_symbol=pe_symbol,
            underlying=underlying,
            ce_power=ce_power,
            ce_list=ce_list,
            ce_crossover=ce_cross,
            pe_power=pe_power,
            pe_list=pe_list,
            pe_crossover=pe_cross,
            idx_power=idx_power,
            idx_list=idx_list,
            idx_crossover=idx_cross,
            ce_sha_debug=ce_sha_dbg,
            pe_sha_debug=pe_sha_dbg,
            idx_sha_debug=idx_sha_dbg,
            # Trend SHA
            ce_trend_power=ce_t_power,
            ce_trend_list=ce_t_list,
            ce_trend_crossover=ce_t_cross,
            pe_trend_power=pe_t_power,
            pe_trend_list=pe_t_list,
            pe_trend_crossover=pe_t_cross,
            idx_trend_power=idx_t_power,
            idx_trend_list=idx_t_list,
            idx_trend_crossover=idx_t_cross,
            ce_trend_sha_debug=ce_t_sha_dbg,
            pe_trend_sha_debug=pe_t_sha_dbg,
            idx_trend_sha_debug=idx_t_sha_dbg,
            # GAP%
            ce_gap=ce_gap,
            pe_gap=pe_gap,
            idx_gap=idx_gap,
            # SHA Relationship
            ce_relationship=ce_rel,
            pe_relationship=pe_rel,
            idx_relationship=idx_rel,
            market_type=market_type,
        )

        return True

    except Exception as e:
        log_strategy_event(
            symbol_key, "UPDATER", "PROCESS_ERROR",
            details=str(e)[:200],
        )
        return False


# ═══════════════════════════════════════════════════════════════════════════════
#  MAIN
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    mode = (sys.argv[1] if len(sys.argv) > 1 else "demo").lower()

    # State writer → C:/Ballom_FYR/state/demo/ or .../live/
    configure_state_writer(mode)

    # ── Fyers client ───────────────────────────────────────────────────────
    fyers: Fyers = DemoFyers() if mode == "demo" else Fyers()

    # ── Load token (written by dev_scanner) ────────────────────────────────
    current_day = date.today()
    session_ok = load_fyers_session(fyers, force=False)

    if session_ok:
        log_strategy_event(
            "SYSTEM", "INIT", "TOKEN_LOADED",
            details=f"Updater started — token loaded for {current_day}",
        )
    else:
        log_strategy_event(
            "SYSTEM", "INIT", "TOKEN_MISSING",
            details="Waiting for dev_scanner to write token...",
        )

    # ── Load holidays ──────────────────────────────────────────────────────
    holidays: set[str] = set()
    special_sessions: list = []
    try:
        holidays, special_sessions = Fyers.load_holiday_set(current_day.year)
        if current_day.month == 12:
            Fyers.fetch_trading_holidays(current_day.year + 1)
    except Exception:
        pass

    write_app_status(
        mode, str(current_day), status="started",
        message=f"Updater started — session {'OK' if session_ok else 'WAITING'}",
    )

    # ══════════════════════════════════════════════════════════════════════════
    #  FOREVER LOOP
    # ══════════════════════════════════════════════════════════════════════════
    while True:
        today = date.today()
        now = datetime.now()
        current_time = now.time()

        # ── Step 1: Day-change → reload token + holidays ───────────────────
        if today != current_day:
            current_day = today
            session_ok = False

            # Reload token (dev_scanner refreshes at midnight)
            # Retry a few times since scanner might still be authenticating
            for attempt in range(6):
                session_ok = load_fyers_session(fyers, force=True)
                if session_ok:
                    break
                sleep(10)

            if session_ok:
                log_strategy_event(
                    "SYSTEM", "UPDATER", "NEW_DAY_TOKEN_OK",
                    details=f"Day change — token reloaded for {current_day}",
                )
            else:
                log_strategy_event(
                    "SYSTEM", "UPDATER", "NEW_DAY_TOKEN_FAIL",
                    details="Token reload failed — will retry each cycle",
                )

            # Refresh holidays
            try:
                holidays, special_sessions = Fyers.load_holiday_set(today.year)
                if today.month == 12:
                    Fyers.fetch_trading_holidays(today.year + 1)
            except Exception:
                pass

            write_app_status(
                mode, str(current_day), status="new_day",
                message=f"Updater new day — token {'OK' if session_ok else 'WAITING'}",
            )

        # ── Step 1b: Retry session if not ready ────────────────────────────
        if not session_ok:
            session_ok = load_fyers_session(fyers, force=True)
            if not session_ok:
                write_app_status(
                    mode, str(current_day), status="waiting_token",
                    message="Waiting for dev_scanner to write token...",
                )
                sleep(15)
                continue

        # ── Step 2: Holiday check ──────────────────────────────────────────
        if not is_trading_day(today, holidays, special_sessions):
            write_app_status(
                mode, str(current_day), status="holiday",
                message="Market holiday — updater idle",
            )
            sleep(60)
            continue

        # ── Step 3: Determine active market window ─────────────────────────
        in_idx_window = INDICES_START <= current_time <= INDICES_END
        in_com_window = COMMODITY_START <= current_time <= COMMODITY_END

        if not in_idx_window and not in_com_window:
            write_app_status(
                mode, str(current_day), status="idle",
                message=f"Outside market hours ({now.strftime('%H:%M')})",
            )
            sleep(UPDATE_INTERVAL)
            continue

        # ── Step 4: Load pairs from dev_scanner's JSON output ──────────────
        symbols_processed = 0
        symbols_failed = 0

        # Process INDEX pairs during index window
        if in_idx_window:
            idx_pairs = _load_json(OPTION_PAIRS_JSON)
            for symbol_key, info in idx_pairs.items():
                ce = info.get("CE", "")
                pe = info.get("PE", "")
                underlying = info.get("indices", "")
                if not ce or not pe or not underlying:
                    continue

                ok = process_symbol(
                    fyers, symbol_key, ce, pe, underlying,
                    market_type="INDEX",
                    holidays=holidays,
                    special_sessions=special_sessions,
                )
                if ok:
                    symbols_processed += 1
                else:
                    symbols_failed += 1

        # Process COMMODITY pairs during commodity window
        if in_com_window:
            com_pairs = _load_json(COMMODITY_PAIRS_JSON)
            for symbol_key, info in com_pairs.items():
                ce = info.get("CE", "")
                pe = info.get("PE", "")
                underlying = info.get("commodity", "")
                if not ce or not pe or not underlying:
                    continue

                ok = process_symbol(
                    fyers, symbol_key, ce, pe, underlying,
                    market_type="COMMODITY",
                    holidays=holidays,
                    special_sessions=special_sessions,
                )
                if ok:
                    symbols_processed += 1
                else:
                    symbols_failed += 1

        # ── Step 5: Update status ──────────────────────────────────────────
        write_app_status(
            mode, str(current_day), status="running",
            in_indices_window=in_idx_window,
            in_commodity_window=in_com_window,
            indices_scanned=in_idx_window,
            commodities_scanned=in_com_window,
            message=(
                f"Updated {symbols_processed} symbol(s) "
                f"{'| ' + str(symbols_failed) + ' failed ' if symbols_failed else ''}"
                f"@ {now.strftime('%H:%M:%S')}"
            ),
        )

        sleep(UPDATE_INTERVAL)


if __name__ == "__main__":
    main()
